server:
  port: 8081

spring:
  rabbitmq:
    host: "localhost"
    port: 5672

  sql:
    init:
      platform: postgresql
  datasource:

    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: none
    sql:
      init:
        mode: always

  application:
    name: message-analyzer

  zipkin:
    enabled: ${ZIPKIN_MODE:false}

rabbit:
  queue:
    common-monitoring-queue: "common_monitoring"